//lifted from https://github.com/pepijndevos/arduino-boy/blob/pokemon go/pokemon constants.h and modified to be an string array, not a typedef enum.
const char *species_index[256] = {
	"Empty Slot",
	"RHYDON",
	"KANGASKHAN",
	"NIDORAN M",
	"CLEFAIRY",
	"SPEAROW",
	"VOLTORB",
	"NIDOKING",
	"SLOWBRO",
	"IVYSAUR",
	"EXEGGUTOR",
	"LICKITUNG",
	"EXEGGCUTE",
	"GRIMER",
	"GENGAR",
	"NIDORAN F",
	"NIDOQUEEN",
	"CUBONE",
	"RHYHORN",
	"LAPRAS",
	"ARCANINE",
	"MEW",
	"GYARADOS",
	"SHELLDER",
	"TENTACOOL",
	"GASTLY",
	"SCYTHER",
	"STARYU",
	"BLASTOISE",
	"PINSIR",
	"TANGELA",
	"MISSINGNO 0x1F",
	"MISSINGNO 0x20",
	"GROWLITHE",
	"ONIX",
	"FEAROW",
	"PIDGEY",
	"SLOWPOKE",
	"KADABRA",
	"GRAVELER",
	"CHANSEY",
	"MACHOKE",
	"MR MIME",
	"HITMONLEE",
	"HITMONCHAN",
	"ARBOK",
	"PARASECT",
	"PSYDUCK",
	"DROWZEE",
	"GOLEM",
	"MISSINGNO 0x32",
	"MAGMAR",
	"MISSINGNO 0x34",
	"ELECTABUZZ",
	"MAGNETON",
	"KOFFING",
	"MISSINGNO 0x38",
	"MANKEY",
	"SEEL",
	"DIGLETT",
	"TAUROS",
	"MISSINGNO 0x3D",
	"MISSINGNO 0x3E",
	"MISSINGNO 0x3F",
	"FARFETCHD",
	"VENONAT",
	"DRAGONITE",
	"MISSINGNO 0x43",
	"MISSINGNO 0x44",
	"MISSINGNO 0x45",
	"DODUO",
	"POLIWAG",
	"JYNX",
	"MOLTRES",
	"ARTICUNO",
	"ZAPDOS",
	"DITTO",
	"MEOWTH",
	"KRABBY",
	"MISSINGNO 0x4F",
	"MISSINGNO 0x50",
	"MISSINGNO 0x51",
	"VULPIX",
	"NINETALES",
	"PIKACHU",
	"RAICHU",
	"MISSINGNO 0x56",
	"MISSINGNO 0x57",
	"DRATINI",
	"DRAGONAIR",
	"KABUTO",
	"KABUTOPS",
	"HORSEA",
	"SEADRA",
	"MISSINGNO 0x5E",
	"MISSINGNO 0x5F",
	"SANDSHREW",
	"SANDSLASH",
	"OMANYTE",
	"OMASTAR",
	"JIGGLYPUFF",
	"WIGGLYTUFF",
	"EEVEE",
	"FLAREON",
	"JOLTEON",
	"VAPOREON",
	"MACHOP",
	"ZUBAT",
	"EKANS",
	"PARAS",
	"POLIWHIRL",
	"POLIWRATH",
	"WEEDLE",
	"KAKUNA",
	"BEEDRILL",
	"MISSINGNO 0x73",
	"DODRIO",
	"PRIMEAPE",
	"DUGTRIO",
	"VENOMOTH",
	"DEWGONG",
	"MISSINGNO 0x79",
	"MISSINGNO 0x7A",
	"CATERPIE",
	"METAPOD",
	"BUTTERFREE",
	"MACHAMP",
	"MISSINGNO 0x7F",
	"GOLDUCK",
	"HYPNO",
	"GOLBAT",
	"MEWTWO",
	"SNORLAX",
	"MAGIKARP",
	"MISSINGNO 0x86",
	"MISSINGNO 0x87",
	"MUK",
	"MISSINGNO 0x8A",
	"KINGLER",
	"CLOYSTER",
	"MISSINGNO 0x8C",
	"ELECTRODE",
	"CLEFABLE",
	"WEEZING",
	"PERSIAN",
	"MAROWAK",
	"MISSINGNO 0x92",
	"HAUNTER",
	"ABRA",
	"ALAKAZAM",
	"PIDGEOTTO",
	"PIDGEOT",
	"STARMIE",
	"BULBASAUR",
	"VENUSAUR",
	"TENTACRUEL",
	"MISSINGNO 0x9C",
	"GOLDEEN",
	"SEAKING",
	"MISSINGNO 0x9F",
	"MISSINGNO 0xA0",
	"MISSINGNO 0xA1",
	"MISSINGNO 0xA2",
	"PONYTA",
	"RAPIDASH",
	"RATTATA",
	"RATICATE",
	"NIDORINO",
	"NIDORINA",
	"GEODUDE",
	"PORYGON",
	"AERODACTYL",
	"MISSINGNO 0xAC",
	"MAGNEMITE",
	"MISSINGNO 0xAE",
	"MISSINGNO 0xAF",
	"CHARMANDER",
	"SQUIRTLE",
	"CHARMELEON",
	"WARTORTLE",
	"CHARIZARD",
	"MISSINGNO 0xB5",
	"FOSSIL KABUTOPS",
	"FOSSIL AERODACTYL",
	"MON GHOST",
	"ODDISH",
	"GLOOM",
	"VILEPLUME",
	"BELLSPROUT",
	"WEEPINBELL",
	"VICTREEBEL",
	"MISSINGNO 0xBF",
	"MISSINGNO 0xC0",
	"MISSINGNO 0xC1",
	"MISSINGNO 0xC2",
	"MISSINGNO 0xC3",
	"MISSINGNO 0xC4",
	"MISSINGNO 0xC5",
	"MISSINGNO 0xC6",
	"MISSINGNO 0xC7",
	"MISSINGNO 0xC8",
	"MISSINGNO 0xC9",
	"MISSINGNO 0xCA",
	"MISSINGNO 0xCB",
	"MISSINGNO 0xCC",
	"MISSINGNO 0xCD",
	"MISSINGNO 0xCE",
	"MISSINGNO 0xCF",
	"MISSINGNO 0xD0",
	"MISSINGNO 0xD1",
	"MISSINGNO 0xD2",
	"MISSINGNO 0xD3",
	"MISSINGNO 0xD4",
	"MISSINGNO 0xD5",
	"MISSINGNO 0xD6",
	"MISSINGNO 0xD7",
	"MISSINGNO 0xD8",
	"MISSINGNO 0xD9",
	"MISSINGNO 0xDA",
	"MISSINGNO 0xDB",
	"MISSINGNO 0xDC",
	"MISSINGNO 0xDD",
	"MISSINGNO 0xDE",
	"MISSINGNO 0xDF",
	"MISSINGNO 0xE0",
	"MISSINGNO 0xE1",
	"MISSINGNO 0xE2",
	"MISSINGNO 0xE3",
	"MISSINGNO 0xE4",
	"MISSINGNO 0xE5",
	"MISSINGNO 0xE6",
	"MISSINGNO 0xE7",
	"MISSINGNO 0xE8",
	"MISSINGNO 0xE9",
	"MISSINGNO 0xEA",
	"MISSINGNO 0xEB",
	"MISSINGNO 0xEC",
	"MISSINGNO 0xED",
	"MISSINGNO 0xEE",
	"MISSINGNO 0xEF",
	"MISSINGNO 0xF0",
	"MISSINGNO 0xF1",
	"MISSINGNO 0xF2",
	"MISSINGNO 0xF3",
	"MISSINGNO 0xF4",
	"MISSINGNO 0xF5",
	"MISSINGNO 0xF6",
	"MISSINGNO 0xF7",
	"MISSINGNO 0xF8",
	"MISSINGNO 0xF9",
	"MISSINGNO 0xFA",
	"MISSINGNO 0xFB",
	"MISSINGNO 0xFC",
	"MISSINGNO 0xFD",
	"MISSINGNO 0xFE",
	"MISSINGNO 0xFF"
};

const char *move_index[256] = {
	"Empty Slot",
	"Pound",
	"Karate Chop",
	"Double Slap",
	"Comet Punch",
	"Mega Punch",
	"Pay Day",
	"Fire Punch",
	"Ice Punch",
	"Thunder Punch",
	"Scratch",
	"Vise Grip",
	"Guillotine",
	"Razor Wind",
	"Swords Dance",
	"Cut",
	"Gust",
	"Wing Attack",
	"Whirlwind",
	"Fly",
	"Bind",
	"Slam",
	"Vine Whip",
	"Stomp",
	"Double Kick",
	"Mega Kick",
	"Jump Kick",
	"Rolling Kick",
	"Sand Attack",
	"Headbutt",
	"Horn Attack",
	"Fury Attack",
	"Horn Drill",
	"Tackle",
	"Body Slam",
	"Wrap",
	"Take Down",
	"Thrash",
	"Double-Edge",
	"Tail Whip",
	"Poison Sting",
	"Twineedle",
	"Pin Missile",
	"Leer",
	"Bite",
	"Growl",
	"Roar",
	"Sing",
	"Supersonic",
	"Sonic Boom",
	"Disable",
	"Acid",
	"Ember",
	"Flamethrower",
	"Mist",
	"Water Gun",
	"Hydro Pump",
	"Surf",
	"Ice Beam",
	"Blizzard",
	"Psybeam",
	"Bubble Beam",
	"Aurora Beam",
	"Hyper Beam",
	"Peck",
	"Drill Peck",
	"Submission",
	"Low Kick",
	"Counter",
	"Seismic Toss",
	"Strength",
	"Absorb",
	"Mega Drain",
	"Leech Seed",
	"Growth",
	"Razor Leaf",
	"Solar Beam",
	"Poison Powder",
	"Stun Spore",
	"Sleep Powder",
	"Petal Dance",
	"String Shot",
	"Dragon Rage",
	"Fire Spin",
	"Thunder Shock",
	"Thunderbolt",
	"Thunder Wave",
	"Thunder",
	"Rock Throw",
	"Earthquake",
	"Fissure",
	"Dig",
	"Toxic",
	"Confusion",
	"Psychic",
	"Hypnosis",
	"Meditate",
	"Agility",
	"Quick Attack",
	"Rage",
	"Teleport",
	"Night Shade",
	"Mimic",
	"Screech",
	"Double Team",
	"Recover",
	"Harden",
	"Minimize",
	"Smokescreen",
	"Confuse Ray",
	"Withdraw",
	"Defense Curl",
	"Barrier",
	"Light Screen",
	"Haze",
	"Reflect",
	"Focus Energy",
	"Bide",
	"Metronome",
	"Mirror Move",
	"Self-Destruct",
	"Egg Bomb",
	"Lick",
	"Smog",
	"Sludge",
	"Bone Club",
	"Fire Blast",
	"Waterfall",
	"Clamp",
	"Swift",
	"Skull Bash",
	"Spike Cannon",
	"Constrict",
	"Amnesia",
	"Kinesis",
	"Soft-Boiled",
	"High Jump Kick",
	"Glare 	Normal",
	"Dream Eater",
	"Poison Gas",
	"Barrage",
	"Leech Life",
	"Lovely Kiss",
	"Sky Attack",
	"Transform",
	"Bubble",
	"Dizzy Punch",
	"Spore",
	"Flash",
	"Psywave",
	"Splash",
	"Acid Armor",
	"Crabhammer",
	"Explosion",
	"Fury Swipes",
	"Bonemerang",
	"Rest",
	"Rock Slide",
	"Hyper Fang",
	"Sharpen",
	"Conversion",
	"Tri Attack",
	"Super Fang",
	"Slash",
	"Substitute",
	"Struggle",
	"Invalid Move 0xA6",
	"Invalid Move 0xA7",
	"Invalid Move 0xA8",
	"Invalid Move 0xA9",
	"Invalid Move 0xAA",
	"Invalid Move 0xAB",
	"Invalid Move 0xAC",
	"Invalid Move 0xAD",
	"Invalid Move 0xAE",
	"Invalid Move 0xAF",
	"Invalid Move 0xB0",
	"Invalid Move 0xB1",
	"Invalid Move 0xB2",
	"Invalid Move 0xB3",
	"Invalid Move 0xB4",
	"Invalid Move 0xB5",
	"Invalid Move 0xB6",
	"Invalid Move 0xB7",
	"Invalid Move 0xB8",
	"Invalid Move 0xB9",
	"Invalid Move 0xBA",
	"Invalid Move 0xBB",
	"Invalid Move 0xBC",
	"Invalid Move 0xBD",
	"Invalid Move 0xBE",
	"Invalid Move 0xBF",
	"Invalid Move 0xC0",
	"Invalid Move 0xC1",
	"Invalid Move 0xC2",
	"Invalid Move 0xC3",
	"Invalid Move 0xC4",
	"Invalid Move 0xC5",
	"Invalid Move 0xC6",
	"Invalid Move 0xC7",
	"Invalid Move 0xC8",
	"Invalid Move 0xC9",
	"Invalid Move 0xCA",
	"Invalid Move 0xCB",
	"Invalid Move 0xCC",
	"Invalid Move 0xCD",
	"Invalid Move 0xCE",
	"Invalid Move 0xCF",
	"Invalid Move 0xD0",
	"Invalid Move 0xD1",
	"Invalid Move 0xD2",
	"Invalid Move 0xD3",
	"Invalid Move 0xD4",
	"Invalid Move 0xD5",
	"Invalid Move 0xD6",
	"Invalid Move 0xD7",
	"Invalid Move 0xD8",
	"Invalid Move 0xD9",
	"Invalid Move 0xDA",
	"Invalid Move 0xDB",
	"Invalid Move 0xDC",
	"Invalid Move 0xDD",
	"Invalid Move 0xDE",
	"Invalid Move 0xDF",
	"Invalid Move 0xE0",
	"Invalid Move 0xE1",
	"Invalid Move 0xE2",
	"Invalid Move 0xE3",
	"Invalid Move 0xE4",
	"Invalid Move 0xE5",
	"Invalid Move 0xE6",
	"Invalid Move 0xE7",
	"Invalid Move 0xE8",
	"Invalid Move 0xE9",
	"Invalid Move 0xEA",
	"Invalid Move 0xEB",
	"Invalid Move 0xEC",
	"Invalid Move 0xED",
	"Invalid Move 0xEE",
	"Invalid Move 0xEF",
	"Invalid Move 0xF0",
	"Invalid Move 0xF1",
	"Invalid Move 0xF2",
	"Invalid Move 0xF3",
	"Invalid Move 0xF4",
	"Invalid Move 0xF5",
	"Invalid Move 0xF6",
	"Invalid Move 0xF7",
	"Invalid Move 0xF8",
	"Invalid Move 0xF9",
	"Invalid Move 0xFA",
	"Invalid Move 0xFB",
	"Invalid Move 0xFC",
	"Invalid Move 0xFD",
	"Invalid Move 0xFE",
	"Invalid Move 0xFF",
};